branchName: '${issue.number}'
branches:
  - label: '🐞 Bug Fix'
    prefix: bug/
  - label: '🌎 Deploy'
    prefix: deploy/
  - label: '📜 Document'
    prefix: doc/
  - label: '✨ Feature'
    prefix: feat/
  - label: '🔨Refactoring'
    prefix: refactoring/
  - label: '✅ Test'
    prefix: test/
    
autoCloseIssue: true
